navbar:
  blog_title: xuweiqiang's blog
  menu:
    - { key: '主题', link: '/', icon: 'iconfont icon-home-fill' }
    - { key: '列表', link: '/archives/', icon: 'iconfont icon-tags-fill' }
    - { key: '分类', link: '/categories/', icon: 'iconfont icon-tags-fill' }
    - { key: '标签', link: '/tags/', icon: 'iconfont icon-tags-fill' }
    - { key: '关于', link: '/about/', icon: 'iconfont icon-user-fill', name: '联系我' }
index:
  slogan:
    enable: true
    text: 找寻热爱~
    api:
      enable: false
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]
